### ISSUE TITLE
Question about `this` example

### ISSUE THREAD

**Issue by samrae7** [JeremyLikness/intro-to-typescript#1]
Hey I hope it's ok to post this here. i'm trying to understand why the code in the lambdas sample works the way it does.

I get the overall point you're making, that lambda functions take their 'this' value from where they're defined, so you don't get so much weirdness.

However I can't see why the code logs undefined for the timeout call in the non-arrow function. My reading around this subject says that the default 'this' for a function is the global context, so how come we don't see

`iterations: 52`

logged ten times for the first timeout call instead of `iterations: undefined`
`
?

Thanks in advance

**Comment by JeremyLikness** [comment]
Which example do you mean? When I cut and paste the code from the lambdas example, the console output is iterations for the ones inside lambdas, and a repeat of "iterations: 32" for the ones outside of the lambda, not undefined. See this link: https://jlik.me/dx9 am I missing something?

**Comment by samrae7** [comment]
Yes I mean that example, but when I compile and run using node as you do in the talk I get undefined logging for the 'iterations' log. You get the same thing (undefined) in your talk: https://www.youtube.com/watch?v=kxkzbMCc8Gg?m=42 so there's something different about the context it's running in. Interesting. Maybe a node thing like it's not using 'use strict'. I will try to work out the difference but just serves to illustrate why `this` plays nicer using arrow functions

**Comment by JeremyLikness** [comment]
Best answer I can give is that investigation shows in the browser, timeout is defined on the window. The undeclared "x" gets attached to the window and is inherited in timeout. In Node, the timeout is attached to a "Timer" object, so x is undefined when the timeout is invoked.
